name: localization_app
description: A localized movie app.

dependencies:
  flutter:
    sdk: flutter
  smooth_star_rating: 1.0.2
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/detail-bg.png
    - assets/l10n/de_CH.json
    - assets/l10n/de_DE.json
    - assets/l10n/en_US.json
    - assets/l10n/es_ES.json
    - assets/l10n/ne_NP.json

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Medium.ttf
          style: normal
        - asset: assets/fonts/Avenir-Heavy.ttf
          weight: 800